parameters:
#    norte_sur_combobox.example.class: NorteSur\ComboboxBundle\Example

services:
#    norte_sur_combobox.example:
#        class: %norte_sur_combobox.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
