parameters:
#    norte_sur_admin.example.class: NorteSur\AdminBundle\Example

services:
#    norte_sur_admin.example:
#        class: %norte_sur_admin.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
